# PostgreSQL. Versions 9.1 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On OS X with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# On OS X with MacPorts:
#   gem install pg -- --with-pg-config=/opt/local/lib/postgresql84/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem 'pg'
#

default: &default
  adapter: postgresql
  host: localhost
  username: myapp
  password: myapp
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000


development:
  <<: *default
  database: railsTraining_development
  username: myapp
  password: myapp

test:
  <<: *default
  database: railsTraining_test
  username: myapp
  password: myapp

production:
  <<: *default
  database: myapp
  username: myapp
  password: <%= ENV['RAILSTRAINING_DATABASE_PASSWORD'] %>
